version: '3'

services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:alpine
    restart: always
    command: ["redis-server", "--requirepass", "password"]
    ports:
      - '6379:6379'

  rails:
    image: chatwoot:latest
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=chatwoot
      - REDIS_URL=redis://:password@redis:6379
      - SECRET_KEY_BASE=your_secret_key_base_here
      - FRONTEND_URL=http://localhost:3000
    command: >
      sh -c "
        bundle exec rails db:create db:migrate &&
        bundle exec rails server -b 0.0.0.0 -p 3000
      "

volumes:
  postgres_test: